version: '3.7'

services:
  # mongodb
  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: anaskhafaga
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      app:
    volumes:
      - db:/data/db
      - configdb:/data/configdb

  # redis [cache]
  redis:
    image: redis:rc-alpine3.11
    volumes:
      - cache:/data
    networks:
      app:

  # Dashboard
  app:
    image: anaskhafaga/dash1
    ports:
      - 8080:80
    links: 
      - "mongo"
      - "redis"
    networks:
      app:


volumes:
  db:
  configdb:
  cache:

networks:
  app: